# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workout',
            managers=[
            ],
        ),
    ]
