# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20161024_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.Exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='uploads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.Attachment'),
        ),
    ]
