# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20161024_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_measurement', models.CharField(choices=[('k', 'kg'), ('l', 'lbs')], default='l', max_length=1)),
                ('repetitions', models.PositiveIntegerField()),
                ('set_type', models.CharField(choices=[('d', 'Drop'), ('n', 'Negative'), ('p', 'Positive'), ('s', 'Super'), ('r', 'Regular')], default='r', max_length=1)),
                ('notes', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='N/A', max_length=80),
        ),
        migrations.AddField(
            model_name='exercise',
            name='notes',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.Set'),
        ),
    ]
