# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_exercise_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout.Exercise'),
            preserve_default=False,
        ),
    ]
