# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_auto_20161025_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
