# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_auto_20161025_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ('date',)},
        ),
    ]
