# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_remove_workout_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='title',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
