# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0014_workout_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
