# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 04:33
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('neck', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('chest', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('navel', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('waist', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('quads', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('biceps', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('forearms', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_measurement_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('about', models.TextField(blank=True)),
                ('avatar', models.ImageField(upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.Profile'),
        ),
    ]
