# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 04:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workout',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 4, 39, 44, 719732, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='location',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
